version: "3.1"
services:

  mariadb:
    image: mariadb:10.4
    container_name: emp-db
    restart: always
    working_dir: /var/lib/mysql
    volumes:
      - ./data/mariadb:/var/lib/mysql
    env_file:
      - ./conf/mariadb/db.env
    ports:
      - "8084:3306"
  
  nginx:
    image: nginx:alpine
    container_name: emp-web
    working_dir: /var/www/html
    volumes:
      - ./data/apps:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"

  php-fpm:
    build: conf/php-fpm
    container_name: emp-php
    working_dir: /var/www/html
    volumes:
      - ./data/apps:/var/www/html
      - ./conf/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

networks:
  default:
    external:
      name: emp-base