version: "3.1"
services:

  consul:
    build: conf/consul
    container_name: emp-autodiscovery
    working_dir: /consul
    volumes:
      - ./data/autodiscovery:/consul/data
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    ports:
      - "8500:8500"
    dns:
      - 127.0.0.1
    deploy:
      resources:
        limits:
          memory: 128M

  mariadb:
    image: mariadb:10.4
    container_name: emp-db
    restart: always
    working_dir: /var/lib/mysql
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - ./conf/mariadb/db.env
    environment:
      - CONSUL=consul
    ports:
      - "8890:3306"
  
  nginx:
    image: nginx:alpine
    container_name: emp-web
    working_dir: /var/www/html
    volumes:
      - ./data/apps:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs:/var/log/nginx
    environment:
      - CONSUL=consul
    ports:
      - "80:80"

  php-fpm:
    build: conf/php-fpm
    container_name: emp-php
    working_dir: /var/www/html
    volumes:
      - ./data/apps:/var/www/html
      - ./conf/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
  
  composer:
    build: conf/composer
    container_name: emp-composer
    working_dir: /var/www/html
    volumes:
      - ./data/apps:/var/www/html

networks:
  default:
    external:
      name: emp-base